# Each new term in the Fibonacci sequence is generated by adding the previous two terms, starting with 1 and 2.
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# initialise array with the first two fibonacci numbers
fibonacci = [1, 2]
even_sum = 2

# use a while loop to calculate next number in the sequence (if below four million) and push to array
while (fibonacci[-1] + fibonacci[-2]) < 4000000:
    next_value = fibonacci[-1] + fibonacci[-2]
    fibonacci.append(next_value)
    if (next_value % 2) == 0:
        even_sum += next_value

# print sum of even numbers
print(even_sum)